### ISSUE TITLE
MAX_BAND_SIZE is enormus.

### ISSUE THREAD

**Issue by NoNaeAbC** [overflowerror/oop-benchmarks#2]
MAX_BAND_SIZE is 2^16 * sizeof(int) = 262144 bytes most of the time is spend zeroing the band which makes the benchmark kind of pointless.

**Comment by sigmasternchen** [comment]
Yeah, that's true. Thanks for pointing it out!

**Comment by sigmasternchen** [comment]
I'll add a note about that to the blog post later one.
